-- Esquema base de pólizas y riesgos.
-- SQL portable: se ejecuta igual en PostgreSQL y en H2 (MODE=PostgreSQL).

CREATE TABLE polizas (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                VARCHAR(30)    NOT NULL,
    tipo                  VARCHAR(20)    NOT NULL,
    estado                VARCHAR(20)    NOT NULL,
    tomador_documento     VARCHAR(20)    NOT NULL,
    tomador_nombre        VARCHAR(150)   NOT NULL,
    fecha_inicio_vigencia DATE           NOT NULL,
    fecha_fin_vigencia    DATE           NOT NULL,
    meses_vigencia        INTEGER        NOT NULL,
    valor_canon           NUMERIC(15, 2) NOT NULL,
    valor_prima           NUMERIC(15, 2) NOT NULL,
    fecha_cancelacion     TIMESTAMP WITH TIME ZONE,
    version               BIGINT         NOT NULL DEFAULT 0,
    creado_en             TIMESTAMP WITH TIME ZONE NOT NULL,
    actualizado_en        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_polizas_numero UNIQUE (numero),
    CONSTRAINT ck_polizas_tipo CHECK (tipo IN ('INDIVIDUAL', 'COLECTIVA')),
    CONSTRAINT ck_polizas_estado CHECK (estado IN ('ACTIVA', 'RENOVADA', 'CANCELADA')),
    CONSTRAINT ck_polizas_meses CHECK (meses_vigencia > 0),
    CONSTRAINT ck_polizas_canon CHECK (valor_canon > 0),
    CONSTRAINT ck_polizas_vigencia CHECK (fecha_fin_vigencia > fecha_inicio_vigencia)
);

CREATE TABLE riesgos (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poliza_id              BIGINT       NOT NULL,
    direccion_inmueble     VARCHAR(200) NOT NULL,
    ciudad                 VARCHAR(80)  NOT NULL,
    arrendatario_documento VARCHAR(20)  NOT NULL,
    arrendatario_nombre    VARCHAR(150) NOT NULL,
    arrendador_documento   VARCHAR(20)  NOT NULL,
    arrendador_nombre      VARCHAR(150) NOT NULL,
    estado                 VARCHAR(20)  NOT NULL,
    fecha_cancelacion      TIMESTAMP WITH TIME ZONE,
    version                BIGINT       NOT NULL DEFAULT 0,
    creado_en              TIMESTAMP WITH TIME ZONE NOT NULL,
    actualizado_en         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_riesgos_poliza FOREIGN KEY (poliza_id) REFERENCES polizas (id),
    CONSTRAINT ck_riesgos_estado CHECK (estado IN ('ACTIVO', 'CANCELADO'))
);

-- Soportan las consultas del API: listado por tipo/estado y riesgos por póliza (FK indexada).
CREATE INDEX ix_polizas_tipo_estado ON polizas (tipo, estado);
CREATE INDEX ix_riesgos_poliza_id ON riesgos (poliza_id);
